spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/russ?characterEncoding=utf-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect #MySQL57Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  http:
    encoding:
      enabled: true  
      force: true  
  messages:
    encoding: UTF-8
mybatis:
  type-aliases-package: com.ysd.entity
  mapper-locations:
  - classpath:mapper/*.xml

